CREATE TABLE IF NOT EXISTS ingredient_lookup (
    canonical TEXT PRIMARY KEY,
    synonyms TEXT,
    category TEXT,
    exceptions TEXT
);

INSERT INTO ingredient_lookup (canonical, synonyms, category, exceptions)
VALUES
  ('onion', 'onion,onions,pyaz,shallot,scallion,spring onion', 'Vegetables', NULL),
  ('garlic', 'garlic,lahsun,garlic clove,garlic cloves', 'Vegetables', NULL),
  ('tomato', 'tomato,tomatoes,tamatar', 'Vegetables', NULL),
  ('rice', 'rice,basmati rice,chawal,brown rice,white rice', 'Grains & Bakery', NULL),
  ('lentil', 'lentil,dal,moong dal,masoor dal,toor dal', 'Grains & Bakery', NULL),
  ('yogurt', 'yogurt,dahi,curd', 'Dairy', NULL),
  ('chicken', 'chicken,murgh,poultry', 'Meat & Seafood', NULL),
  ('beef', 'beef,gomash', 'Meat & Seafood', NULL),
  ('potato', 'potato,aloo', 'Vegetables', NULL),
  ('oil', 'oil,cooking oil,mustard oil,olive oil,vegetable oil', 'Condiments & Spices', 'soy sauce,fish sauce'),
  ('salt', 'salt,namak,sea salt,table salt', 'Condiments & Spices', NULL),
  ('pepper', 'pepper,black pepper,kali mirch', 'Condiments & Spices', NULL),
  ('turmeric', 'turmeric,haldi', 'Condiments & Spices', NULL),
  ('chili powder', 'chili powder,red chili powder,lal mirch powder', 'Condiments & Spices', NULL),
  ('coriander', 'coriander,dhaniya', 'Condiments & Spices', NULL),
  ('ginger', 'ginger,adrak', 'Condiments & Spices', NULL),
  ('butter', 'butter,makhan', 'Dairy', NULL),
  ('cream', 'cream,malai,heavy cream', 'Dairy', NULL),
  ('milk', 'milk,doodh', 'Dairy', NULL),
  ('flour', 'flour,atta,maida', 'Grains & Bakery', NULL),
  ('egg', 'egg,eggs,anda', 'Meat & Seafood', NULL),
  ('banana', 'banana,kela', 'Fruits', NULL),
  ('apple', 'apple,seb', 'Fruits', NULL),
  ('mango', 'mango,aam', 'Fruits', NULL),
  ('coconut', 'coconut,nariyal', 'Other', NULL),
  ('cumin', 'cumin,jeera', 'Condiments & Spices', NULL),
  ('garam masala', 'garam masala', 'Condiments & Spices', NULL),
  ('mustard seeds', 'mustard seeds,rai', 'Condiments & Spices', NULL),
  ('fenugreek', 'fenugreek,methi', 'Condiments & Spices', NULL),
  ('cardamom', 'cardamom,elaichi', 'Condiments & Spices', NULL),
  ('cloves', 'cloves,laung', 'Condiments & Spices', NULL),
  ('cinnamon', 'cinnamon,dalchini', 'Condiments & Spices', NULL),
  ('bay leaves', 'bay leaves,tej patta', 'Condiments & Spices', NULL),
  ('curry leaves', 'curry leaves,kari patta', 'Condiments & Spices', NULL),
  ('ghee', 'ghee,clarified butter', 'Dairy', NULL),
  ('paneer', 'paneer,indian cheese', 'Dairy', NULL),
  ('chickpeas', 'chickpeas,chana,garbanzo beans', 'Grains & Bakery', NULL),
  ('kidney beans', 'kidney beans,rajma', 'Grains & Bakery', NULL),
  ('spinach', 'spinach,palak', 'Vegetables', NULL),
  ('okra', 'okra,bhindi', 'Vegetables', NULL),
  ('eggplant', 'eggplant,baingan,aubergine', 'Vegetables', NULL),
  ('cauliflower', 'cauliflower,gobhi', 'Vegetables', NULL),
  ('green chili', 'green chili,hari mirch', 'Vegetables', NULL),
  ('tamarind', 'tamarind,imli', 'Condiments & Spices', NULL),
  ('coconut milk', 'coconut milk', 'Dairy', NULL);
